connection:
  host: "localhost"
  port: 3306
  database: "db"
  username: "user"
  password: "user"
  driverClass: "com.mysql.cj.jdbc.Driver"
purgeThreads:
  - tableName: test
    whereFilter: WHERE created_at > '2020-01-30' and created_at < 2020-01-30
    limit: 2000
  - tableName: test
    whereFilter: WHERE created_at > '2020-02-01' and created_at < 2020-02-30
    limit: 2000