connection:
  host: "localhost"
  port: 3306
  database: "db"
  username: "user"
  password: "user"
  driverClass: "com.mysql.cj.jdbc.Driver"
purgeThreads:
  - tableName: test
    name: 'delete-older-1'
    whereFilter: WHERE created_at >= '2020-01-01 00:00:00' and created_at < '2020-02-01 10:00:00'
    limit: 2000
  - tableName: test
    name: 'delete-older-2'
    whereFilter: WHERE created_at >= '2020-02-01 00:00:00' and created_at < '2020-03-01 00:00:00'
    limit: 2000
  - tableName: test
    name: 'delete-older-3'
    whereFilter: WHERE created_at <= DATE_SUB(NOW(), INTERVAL 1 SECOND)
    limit: 1
